django_troop/django_troop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("scouts.urls")),
    path("admin/", admin.site.urls),
    path("imports/", include("imports.urls")),
    path("accounts/", include("allauth.urls")),
    path("scouts/", include("scouts.urls")),
    path("adults/", include("scouts.adult_urls")),
    path("users/", include("scouts.user_urls")),
    path("patrols/", include("patrols.urls")),
    path("positions/", include("positions.urls")),
    path("leaders/", include("leaders.urls")),
    path("badges/", include("badges.urls")),
    path("requirement_labels/", include("requirement_labels.urls")),
    path("signoffs/", include("signoffs.urls")),
    path("site_admin/", include("site_admin.urls")),
    path("invitations/", include("invitations.urls", namespace="invitations")),
    path("health/", include("health_check.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns


# accounts/login/ [name='login']
# accounts/logout/ [name='logout']
# accounts/password_change/ [name='password_change']
# accounts/password_change/done/ [name='password_change_done']
# accounts/password_reset/ [name='password_reset']
# accounts/password_reset/done/ [name='password_reset_done']
# accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/reset/done/ [name='password_reset_complete']

django_troop/patrols/urls.py
import patrols.views as views
from django.urls import path

urlpatterns = [
    path("", views.PatrolListView.as_view(), name="patrol_list"),
    path("<int:pk>", views.PatrolDetailView.as_view(), name="patrol_detail"),
    path("update/<int:pk>/", views.PatrolUpdateView.as_view(), name="patrol_update"),
    path("new/", views.PatrolCreateView.as_view(), name="patrol_create"),
    path("delete/<int:pk>/", views.PatrolDeleteView.as_view(), name="patrol_delete"),
]

django_troop/setup/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.setup, name="setup"),
]

django_troop/patrols/models.py
from datetime import date

from django.contrib.auth.models import Group
from django.db import models
from django.urls import reverse_lazy
from leaders.models import Leader
from positions.models import Position


class Patrol(models.Model):
    name = models.CharField(max_length=100)

    def get_absolute_url(self):
        return reverse_lazy("patrol_detail", kwargs={"pk": self.pk})

    def get_leader(self):
        ic()  # noqa
        try:
            return Leader.objects.get(
                end_date__isnull=True, patrol=self, position__name="Patrol Leader"
            )
        except Leader.DoesNotExist:
            return None

    def set_leader(self, user):
        ic()  # noqa
        if not user:
            return None
        if patrol_leader := self.get_leader():
            patrol_leader.end_date = date.today()
            patrol_leader.save()
        patrol_leader_position = Position.objects.get(name="Patrol Leader")
        Leader.objects.create(
            start_date=date.today(),
            patrol=self,
            position=patrol_leader_position,
            user=user,
        )

    def get_mentor(self):
        try:
            return Leader.objects.get(
                end_date__isnull=True, patrol=self, position__name="Patrol Mentor"
            )
        except Leader.DoesNotExist:
            return None

    def set_mentor(self, mentor):
        if not mentor:
            return None
        if mentor_leader := self.get_mentor():
            mentor_leader.end_date = date.today()
            mentor_leader.save()
        patrol_mentor_position = Position.objects.get(name="Patrol Mentor")
        Leader.objects.create(
            start_date=date.today(),
            patrol=self,
            position=patrol_mentor_position,
            user=mentor,
        )


class UserGroup(models.Model):
    description = models.CharField(max_length=100)
    group = models.ForeignKey(
        Group, related_name="group_profile", on_delete=models.CASCADE
    )

django_troop/patrols/forms.py
import logging

from django import forms
from patrols.models import Patrol
from scouts.models import User

logger = logging.getLogger(__name__)


class PatrolForm(forms.ModelForm):
    patrol_members = forms.MultipleChoiceField(
        choices=((None, None)),
    )

    leader = forms.ChoiceField(
        choices=((None, None)),
    )

    mentor = forms.ChoiceField(
        choices=((None, None)),
    )

    class Meta:
        model = Patrol
        fields = [
            "name",
            "patrol_members",
            "leader",
            "mentor",
        ]

    def __init__(self, *args, **kwargs):
        ic()  # noqa
        super().__init__(*args, **kwargs)
        ic(kwargs)  # noqa
        if kwargs.get("instance"):
            qm = kwargs.get("instance").patrol_members
        else:
            qm = User.scouts

        self.fields["patrol_members"] = forms.MultipleChoiceField(
            widget=forms.CheckboxSelectMultiple,
            required=False,
            label="Patrol Members",
            choices=self.get_member_choices(),
        )

        self.fields["leader"] = forms.ModelChoiceField(
            required=False,
            queryset=qm,
        )

        self.fields["mentor"] = forms.ModelChoiceField(
            required=False,
            queryset=User.adults,
        )

        logger.info(self.fields["patrol_members"].initial)

    def get_member_choices(self):
        choices = []
        for scout in User.scouts.order_by("patrol", "last_name").all():
            name_str = f"{scout.first_name} {scout.last_name}"
            if scout.patrol:
                name_str += f" ({scout.patrol.name})"
            else:
                name_str += " (Not assigned)"
            choices.append((scout.pk, name_str))
        return choices

django_troop/patrols/views.py
from badges.models import Badge
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Count, Q
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from patrols.forms import PatrolForm
from patrols.models import Patrol
from requirements.models import Requirement
from scouts.models import User
from signoffs.models import Signoff

TOP_RANK_NEEDS = 5


def set_patrol_members(view, form):
    form.instance.patrol_members.set([])

    for scout in form.cleaned_data.get("patrol_members"):
        form.instance.patrol_members.add(User.objects.get(pk=scout))


def set_patrol_mentor(view, form):
    ic()  # noqa
    if mentor := form.cleaned_data.get("mentor"):
        ic(mentor)  # noqa
        form.instance.mentor(mentor)


def set_patrol_leader(view, form):
    ic()  # noqa
    if leader := form.cleaned_data.get("leader"):
        ic(leader)  # noqa
        form.instance.set_leader(leader)


class PatrolUpdateView(PermissionRequiredMixin, UpdateView):
    model = Patrol
    form_class = PatrolForm
    permission_required = ["patrols.change_patrol"]

    def form_valid(self, form):
        ic()  # noqa
        set_patrol_members(self, form)
        set_patrol_mentor(self, form)
        set_patrol_leader(self, form)
        self.object = form.save()

        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, *args, **kwargs):
        ic()  # noqa
        context = super().get_context_data(*args, **kwargs)
        patrol = self.get_object()
        ic(patrol)  # noqa
        context["form"] = PatrolForm(
            initial={
                "name": patrol.name,
                "patrol_members": [user.id for user in patrol.patrol_members.all()],
                "leader": patrol.get_leader().user.id if patrol.get_leader() else None,
                "mentor": patrol.get_mentor().user.id if patrol.get_mentor() else None,
            }
        )
        return context

    def get_form_kwargs(self):
        ic()  # noqa
        ic(self)  # noqa
        kwargs = super().get_form_kwargs()
        patrol = self.get_object()
        kwargs["initial"] = {
            "patrol_members": [scout.id for scout in patrol.patrol_members.all()],
            "leader": patrol.get_leader().user.id if patrol.get_leader() else [],
            "mentor": patrol.get_mentor().user.id if patrol.get_mentor() else [],
        }
        kwargs["instance"] = patrol

        return kwargs


class PatrolCreateView(PermissionRequiredMixin, CreateView):
    model = Patrol
    form_class = PatrolForm
    permission_required = ("patrols.add_patrol",)

    def form_valid(self, form):
        self.object = form.save()

        set_patrol_members(self, form)
        self.object = form.save()

        return HttpResponseRedirect(self.get_success_url())


class PatrolDeleteView(PermissionRequiredMixin, DeleteView):
    model = Patrol
    success_url = reverse_lazy("patrol_list")
    permission_required = "patrols.change_patrol"


class PatrolListView(LoginRequiredMixin, ListView):
    model = Patrol
    context_object_name = "patrols"
    ordering = "name"


class PatrolDetailView(LoginRequiredMixin, DetailView):
    model = Patrol
    context_object_name = "patrol"
    template_name = "patrols/patrol_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["scouts"] = context["patrol"].patrol_members

        context["mentor"] = context["patrol"].get_mentor()
        context["leader"] = context["patrol"].get_leader()

        context["rank_needs"] = {}

        # take the scouts in this patrol
        # for each rank up to first class
        # and each requirement except those in the "Excludable" group
        # (Scoutmaster Conference, Board of Review, etc)
        # count how many scouts from this patrol still need that requirement
        # sort by count descending and take the TOP_RANK_NEEDS highest for each badge
        #
        for rank in Badge.objects.filter(
            badge_type="rank", order__lte=4, order__gt=0
        ).all():
            context["rank_needs"][rank.order] = (
                Requirement.objects.filter(
                    badge=rank, signoffs__scout__in=context["scouts"].all()
                )
                .exclude(labels__name__contains="Excludable")
                .annotate(count=Count("signoffs__id", filter=Q(signoffs__signed=False)))
                .order_by("-count")
                .exclude(count__lte=0)
                .values(
                    "count",
                    "code",
                    "text",
                    "badge__order",
                    "badge",
                    "badge__id",
                    "badge__name",
                )[:TOP_RANK_NEEDS]
            )

        # scouts to display in patrol advancement table
        context["advancement_scouts"] = (
            context["scouts"]
            .filter(current_rank__order__lte=4)
            .order_by("last_name", "first_name")
        )

        context["signoffs"] = Signoff.objects.filter(
            requirement__badge__badge_type="rank",
            scout__in=context["advancement_scouts"].all(),
            requirement__badge__order__lte=4,
            requirement__badge__order__gte=1,
            scout__current_rank__order__lte=4,
        ).order_by(
            "requirement__badge",
            "requirement__code",
            "scout__last_name",
            "scout__first_name",
        )

        return context

django_troop/patrols/templates/patrols/patrol_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm Delete Patrol {{ object.name }}{% endblock %}

{% block content %}


<form method="post">{% csrf_token %}
	<p>Are you sure you want to delete "{{ object.name }}"?</p>
	<p>Scouts assigned to this patrol will have their patrol un-set</p>
    {{ form }}
    <input type="submit" value="Confirm">
    <a href="{% url 'patrol_list' %}"><button type="button">Cancel</button></a>
</form>


{% endblock %}

django_troop/patrols/templates/patrols/patrol_detail.html
{% extends 'base.html' %}

{% block title %}{{ patrol.name }}{% endblock %}

{% block content %}

<div class="container">

{{ patrol.name }}
{% if leader %}
 led by {{ leader.full_name }}
{% endif %}
{% if mentor and leader %}
, mentored by {{mentor.full_name}}
{% elif mentor %}
 mentored by {{ mentor.full_name }}
{% endif %}



{% if perms.patrols.change_patrol %}
	<span>	<a href="{% url 'patrol_update' patrol.id %}"><button type="button" class="btn btn-primary">Edit Patrol</button></a> </span>
{% endif %}
{% if perms.patrols.delete_patrol %}
	<span><a href="{% url 'patrol_delete' patrol.id %}"><button type="button" class="btn btn-danger">Delete Patrol</button></a></span>
{% endif %}
	<div>
    <div class="col">
    </div>
{% for scout in patrol.patrol_members.all %}
<div>
  <span><a href="{% url 'scouts_detail' pk=scout.id %}">{{scout.safe_name}}</a></span>
  <span class="badge bg-primary">{{scout.current_rank.name}}</span>
  <span>{{ scout.current_rank_date }} </span>
  <span class="progress">
    <span class="progress-bar" role="progressbar" style="width: {{ scout.percent_rank_done | floatformat:0 }}%;" aria-valuenow="{{ scout.percent_rank_done | floatformat:0}}" aria-valuemin="0" aria-valuemax="100">{{ scout.percent_rank_done | floatformat:0}}%</span>
  </span>
</div>
	{% endfor %}

{% if rank_needs %}

<div class="col-8">
    <h3>{{ patrol.name }} Most Needed Requirements</h3>
    <table class="table table-striped table-hover">
	    <thead>
    <tr>
	    <th>Rank</th>
	    <th>Requirement</th>
	    <th>Code</th>
	    <th>Scouts Needing</th>
    </tr>
	    </thead>

	    <tbody>
{% for rank_need in rank_needs.values %}

{% for requirement in rank_need %}
    <tr>
	    <td><a href="{% url 'rank_detail' requirement.badge__id %}">{{ requirement.badge__name }}</a></td>
	    <td>{{ requirement.text }}</td>
	    <td><a href="#requirement-{{requirement.badge__name}}{{requirement.code}}">{{ requirement.code }}</a></td>
	    <td>{{ requirement.count }}</td>
    </tr>

{% endfor %}

{% endfor %}

	    </tbody>
    </table>
    </div>

    {% endif %}
<div>

    </div>
</div>

<div class="container">
    <div class="col">
    </div>
    <div class="col-8">
    <table class="table">
    <tr>
        <th>Rank</th>
        <th>Code</th>
        <th>Requirement</th>
        {% for scout in advancement_scouts.all %}
        <td><a href="{% url "scouts_detail" pk=scout.id %}">{{scout.safe_name}}</a></td>
        {% endfor %}
    </tr>
    {% regroup signoffs by requirement as requirements_list %}

    {% for requirement, scout_data in requirements_list %}

    <tr>

	    <td id="requirement-{{ scout_data.0.requirement.badge.name}}{{scout_data.0.requirement.code}}"><a href="{% url 'rank_detail' scout_data.0.requirement.badge.id %}">{{ scout_data.0.requirement.badge.name }}</a></td>
	    <td> {{ scout_data.0.requirement.code }} </td>
	    <td> {{ scout_data.0.requirement.text }} </td>

{% for data in scout_data %}

    {% if perms.signoffs.signoff_allowed %}
	    {% if data.signed %}
	    <td>{% include "signoffs/mini_signed_off.html" with signoff=data %}</td>
	    {% else %}
	    <td>{% include "signoffs/mini_not_signed_off.html" with signoff=data %}</td>
	    {% endif %}
    {% else %}

	    {% if data.signed %}
	    <td>X</td>
	    {% else %}
	    <td>O</td>
	    {% endif %}
    {% endif %}
{% endfor %}

    </tr>

    {% endfor %}

</table>
    </div>
    <div class="col">
    </div>

</div>

{% endblock %}

django_troop/patrols/templates/patrols/patrol_form.html
{% extends 'base.html' %}

{% block title %}Patrol{% endblock %}

{% block content %}

{% load crispy_forms_tags %}

<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <p><input type="submit" value="Submit"></p>
</form>
{% endblock %}

django_troop/patrols/templates/patrols/patrol_list.html
{% extends 'base.html' %}

{% block title %}Patrols{% endblock %}

{% block content %}
{% if perms.patrols.add_patrol %}
<div> <a href="{% url 'patrol_create' %}"><button type="button" class="btn btn-success">Create New</button></a></div>
{% endif %}



<div class="accordion" id="accordionPatrols">
  {% for patrol in patrols %}
  <div class="accordion-item">
    <h2 class="accordion-header" id="heading{{ patrol.name|slugify }}">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{patrol.name |slugify}}" aria-expanded="false" aria-controls="collapse{{ patrol.name|slugify }}">
	{{ patrol.name }}
      </button>
    </h2>
    <div id="collapse{{patrol.name | slugify}}" class="accordion-collapse collapse" aria-labelledby="heading{{ patrol.name|slugify }}" data-bs-parent="#accordionPatrols">
      <div class="accordion-body">
	<div class="badge bg-light"><a href="{% url 'patrol_detail' pk=patrol.id %}">View Patrol</a></div>
	{% for scout in patrol.patrol_members.all %}
	<div>
	  <span><a href="{% url 'scouts_detail' pk=scout.id %}">{{scout.safe_name}}</a></span>
	  <span class="badge bg-primary">{{scout.current_rank.name}}</span>
	  <span>{{ scout.current_rank_date }} </span>
	  <span class="progress">
	    <span class="progress-bar" role="progressbar" style="width: {{ scout.percent_rank_done | floatformat:0 }}%;" aria-valuenow="{{ scout.percent_rank_done | floatformat:0}}" aria-valuemin="0" aria-valuemax="100">{{ scout.percent_rank_done | floatformat:0}}%</span>
	  </span>
	</div>
	{% endfor %}
      </div>
    </div>
  </div>
  {% endfor %}

</div>

{% endblock %}